# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true

- task: UseDotNet@2
  displayName: 'Use .NET Core 3.x'
  inputs:
    version: 3.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '-c $(buildConfiguration)'

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(Build.SourcesDirectory)'
#     Contents: '**/bin/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
#     FlattenFolders: true

# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(Build.ArtifactStagingDirectory)'
#     artifact: '$(BuildConfiguration)'
